name: eda-anp
channels:
  - conda-forge
dependencies:
  - altair==4.0.1
  - folium==0.10.1
  - geopandas==0.6.2
  - geopy==1.20.0
  - notebook==6.0.3
  - openpyxl==3.0.3
  - python=3.6
  - seaborn==0.9.0
  - statsmodels==0.11.0
  - jupyter==1.0.0
  - jupyter_contrib_nbextensions==0.5.1
  - vega==2.6.0
  - vega3==0.13.0
  - vega_datasets==0.8.0
  - matplotlib==3.1.1
  - numpy==1.18.1
  - pandas==0.25.3
  - scipy==1.3.2
  - xlrd==1.2.0
  - rise==5.6.0
