name: eda-anp
channels:
  - conda-forge
dependencies:
  - altair
  - folium
  - geopandas
  - geopy
  - notebook
  - openpyxl
  - python=3.6
  - seaborn
  - statsmodels
  - jupyter
  - jupyter_contrib_nbextensions
  - vega
  - vega3
  - vega_datasets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - xlrd
  - rise
