name: eda-anp
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - folium
  - geopandas
  - geopy
  - notebook
  - openpyxl
  - python
  - seaborn
  - statsmodels
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - vega
  - vega_datasets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - xlrd
